groups:
  admin:
    members:
      - devinchristianson
    environments:
      - "*"
    overrides: {} # this line is very important for now - also, overrides have a bunch of annoying gotchas
  test:
    members:
      - umcst
    environments:
      - test
      - k3s
    overrides: {} # this line is very important for now - also, overrides have a bunch of annoying gotchas
environments:
  test: {}
  k3s:
    docker:
      execution:
        container:
          image: devinchristianson/k3dlab:2.3
          env:
            - DOMAIN=localhost
        network:
          endpoints:
            - k3d-demo_infra_default
        host:
          binds:
            - "/var/run/docker.sock:/var/run/docker.sock"