groups:
  admin:
    members:
      - devinchristianson
      - devin.a.christianson@gmail.com
    environments:
      - "*"
    overrides: {} # this line is very important for now - also, overrides have a bunch of annoying gotchas
  test:
    members:
      - umcst
    environments:
      - test
      - k3s
    overrides: {} # this line is very important for now - also, overrides have a bunch of annoying gotchas
environments:
  ubuntu:
    config:
      docker:
        execution:
          container:
            image: ssh-lab-factory-ubuntu-lab
  k3s:
    config:
      docker:
        execution:
          container:
            image: devinchristianson/k3dlab:4.2.0
            env:
              - DOMAIN=localhost
          network:
            endpointsconfig:
              ssh-lab-factory_k3s: {} # start in the same network as the cluster
    webhooks:
      initialization: http://k3d-http:8090/$username/cluster/ensurerunning
      cleanup: http://k3d-http:8090/$username/cluster/stop
      files: 
        /home/lab/.kube/config: http://k3d-http:8090/$username/cluster/config