services:
  authconfig:
    build: ./authconfig
    volumes:
      - "./authconfig/data.yml:/config/data.yml"
  containerssh:
    # need to use the alpha because it's the only version that supports newer hot keys than rsa-sha1
    image: containerssh/containerssh:0.5.0-alpha.1
    ports:
      - 127.0.0.1:2222:2222
    volumes:
    - type: bind
      source: ./config.yaml
      target: /etc/containerssh/config.yaml
    - type: bind
      source: ./ssh_host_rsa_key
      target: /var/secrets/ssh_host_rsa_key
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    user: "root"