version: "3.9"

services:
  # only here for building/testing purposes
  k3s-lab:
    profiles:
      - lab-client
    networks:
      - k3s
    build: 
      context: infra/lab-container
      additional_contexts:
        lab: lab
    image: devinchristianson/k3dlab:4.1.0
    user: root
    environment:
      - USERNAME=testuser
      - ENVIRONMENT=k3s
      - DOMAIN=localhost
  k3d-http:
    profiles:
      - k3s
    build: 
      context: infra/k3d-http
    environment:
      - DOMAIN=${DOMAIN}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
      - k3s
  traefik:
    profiles:
      - k3s
    image: "traefik:v2.10"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.kubeapi.address=:6443"
    ports:
      - "80:80"
      - "443:443"
      - "6443:6443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - k3s
    depends_on:
      - whoami
      - error-pages
  whoami:
    profiles:
      - k3s
    image: "traefik/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=HostRegexp(`whoami.localhost`, `{subdomain:[a-z]+}.whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - k3s
  error-pages:
    profiles:
      - k3s
    image: tarampampam/error-pages:2.26.0
    environment:
      TEMPLATE_NAME: l7-dark # set the error pages template
    labels:
      traefik.enable: true
      # use as "fallback" for any NON-registered services (with priority below normal)
      traefik.http.routers.error-pages-router.rule: HostRegexp(`{host:.+}`)
      traefik.http.routers.error-pages-router.priority: 10
      # should say that all of your services work on https
      traefik.http.routers.error-pages-router.entrypoints: web
      traefik.http.routers.error-pages-router.middlewares: error-pages-middleware
      # "errors" middleware settings
      traefik.http.middlewares.error-pages-middleware.errors.status: 400-599
      traefik.http.middlewares.error-pages-middleware.errors.service: error-pages-service
      traefik.http.middlewares.error-pages-middleware.errors.query: /{status}.html
      # define service properties
      traefik.http.services.error-pages-service.loadbalancer.server.port: 8080
    networks:
      - k3s
networks:
  k3s:
  internal: