# kubectl run psql --rm -it -n db --image ongres/postgres-util --restart=Never -- psql -h postgres-ha-postgresql-ha-pgpool postgres postgres
postgresql:
  password: "{{ default_password }}"
  database: postgres 
  repmgrPassword: "{{ default_password }}"
pgpool:
  replicaCount: 2
  adminUsername: postgres
  adminPassword: "{{ default_password }}"