version: "3.9"

services:
  ubuntu-lab:
    build: 
      context: .
    environment:
      - USERNAME=testuser
      - ENVIRONMENT=k3s
      - DOMAIN=localhost
      - DEV=1
    networks:
      - k3s
    stop_grace_period: 20s
    profiles:
      - lab-client