apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: ${USERNAME}
network: ssh-lab-factory_k3s
kubeAPI: # same as `--api-port myhost.my.domain:6445` (where the name would resolve to 127.0.0.1)
  host: "${USERNAME}.${DOMAIN}" # important for the `server` setting in the kubeconfig
  hostIP: "127.0.0.1" # where the Kubernetes API will be listening on
options:
  runtime:
    labels:
      - label: traefik.enable=true
        nodeFilters:
          - server:0
      # proxy HTTP requests
      - label: traefik.http.routers.${USERNAME}-web.rule=HostRegexp(`{subdomain:([a-z-]+.)*}${USERNAME}.${DOMAIN}`)
        nodeFilters:
          - server:0
      - label: traefik.http.routers.${USERNAME}-web.entrypoints=web
        nodeFilters:
          - server:0
      - label: traefik.http.services.${USERNAME}-web.loadbalancer.server.port=80
        nodeFilters:
          - server:0
      - label: traefik.http.routers.${USERNAME}-web.service=${USERNAME}-web
        nodeFilters:
          - server:0
      # pass through HTTPS requests
      - label: traefik.tcp.routers.${USERNAME}-websecure.rule=HostSNIRegexp(`{subdomain:([a-z-]+.)*}${USERNAME}.${DOMAIN}`)
        nodeFilters:
          - server:0
      - label: traefik.tcp.routers.${USERNAME}-websecure.entrypoints=websecure
        nodeFilters:
          - server:0
      - label: traefik.tcp.services.${USERNAME}-websecure.loadbalancer.server.port=443
        nodeFilters:
          - server:0
      - label: traefik.tcp.routers.${USERNAME}-websecure.service=${USERNAME}-websecure
        nodeFilters:
          - server:0
      # route root subdomain to kubeapy
      - label: traefik.enable=true
        nodeFilters:
          - loadbalancer
      - label: traefik.tcp.routers.${USERNAME}-api.rule=HostSNI(`${USERNAME}.${DOMAIN}`)
        nodeFilters:
          - loadbalancer
      - label: traefik.tcp.routers.${USERNAME}-api.entrypoints=kubeapi
        nodeFilters:
          - loadbalancer
      - label: traefik.tcp.routers.${USERNAME}-api.tls.passthrough=true
        nodeFilters:
          - loadbalancer
      - label: traefik.tcp.services.${USERNAME}-api.loadbalancer.server.port=6443
        nodeFilters:
          - loadbalancer
      - label: traefik.tcp.routers.${USERNAME}-api.service=${USERNAME}-api
        nodeFilters:
          - loadbalancer